-- MySQL Script generated by MySQL Workbench
-- Tue Aug 10 14:22:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Winos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Winos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Winos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Winos` ;

-- -----------------------------------------------------
-- Table `Winos`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Winos`.`Admin` (
  `id_admin` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `login` CHAR(55) NULL DEFAULT NULL,
  `mot_de_passe` CHAR(55) NULL DEFAULT NULL,
  PRIMARY KEY (`id_admin`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Winos`.`Blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Winos`.`Blog` (
  `id_article` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `article` CHAR(200) NULL DEFAULT NULL,
  `adress_photo` CHAR(200) NULL DEFAULT NULL,
  `adress_video` CHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_article`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Winos`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Winos`.`Client` (
  `id_client` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `nom` CHAR(55) NULL DEFAULT NULL,
  `prenom` CHAR(55) NULL DEFAULT NULL,
  `date_naissance` DATE NULL DEFAULT NULL,
  `mot_de_passe` CHAR(55) NULL DEFAULT NULL,
  `adress_mail` CHAR(55) NULL DEFAULT NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Winos`.`Coffret`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Winos`.`Coffret` (
  `id_coffret` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `occasion` CHAR(55) NULL DEFAULT NULL,
  `prix` FLOAT NULL DEFAULT NULL,
  `produits` CHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_coffret`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Winos`.`tag_gout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Winos`.`tag_gout` (
  `id_gout` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `descrip` CHAR(55) NULL DEFAULT NULL,
  PRIMARY KEY (`id_gout`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Winos`.`tag_accord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Winos`.`tag_accord` (
  `id_accord` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `descrip` CHAR(55) NULL DEFAULT NULL,
  PRIMARY KEY (`id_accord`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Winos`.`Fournisseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Winos`.`Fournisseur` (
  `id_fournisseur` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `nom` CHAR(55) NULL DEFAULT NULL,
  PRIMARY KEY (`id_fournisseur`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Winos`.`Produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Winos`.`Produit` (
  `id_produit` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `nom` CHAR(55) NOT NULL,
  `cepage` CHAR(55) NULL DEFAULT NULL,
  `provenance` CHAR(55) NULL DEFAULT NULL,
  `millesime` MEDIUMINT NOT NULL,
  `descrip` CHAR(200) NULL DEFAULT NULL,
  `adress_photo` CHAR(200) NULL DEFAULT NULL,
  `tags_gout` MEDIUMINT NULL DEFAULT NULL,
  `tags_accord` MEDIUMINT NULL DEFAULT NULL,
  `categorie_vin` CHAR(55) NULL DEFAULT NULL,
  `couleur` TINYINT(1) NULL DEFAULT NULL,
  `bulles` TINYINT(1) NULL DEFAULT NULL,
  `prix` FLOAT NULL DEFAULT NULL,
  `id_fournisseur` MEDIUMINT NOT NULL,
  PRIMARY KEY (`id_produit`),
  INDEX `tags_gout` (`tags_gout` ASC) VISIBLE,
  INDEX `tags_accord` (`tags_accord` ASC) VISIBLE,
  INDEX `id_fournisseur` (`id_fournisseur` ASC) VISIBLE,
  CONSTRAINT `produit_ibfk_1`
    FOREIGN KEY (`tags_gout`)
    REFERENCES `Winos`.`tag_gout` (`id_gout`),
  CONSTRAINT `produit_ibfk_2`
    FOREIGN KEY (`tags_accord`)
    REFERENCES `Winos`.`tag_accord` (`id_accord`),
  CONSTRAINT `produit_ibfk_3`
    FOREIGN KEY (`id_fournisseur`)
    REFERENCES `Winos`.`Fournisseur` (`id_fournisseur`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Winos`.`Panier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Winos`.`Panier` (
  `id_panier` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `id_client` MEDIUMINT NOT NULL,
  `id_produit` MEDIUMINT NULL DEFAULT NULL,
  `id_coffret` MEDIUMINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_panier`),
  INDEX `id_client` (`id_client` ASC) VISIBLE,
  INDEX `id_produit` (`id_produit` ASC) VISIBLE,
  INDEX `id_coffret` (`id_coffret` ASC) VISIBLE,
  CONSTRAINT `panier_ibfk_1`
    FOREIGN KEY (`id_client`)
    REFERENCES `Winos`.`Client` (`id_client`),
  CONSTRAINT `panier_ibfk_2`
    FOREIGN KEY (`id_produit`)
    REFERENCES `Winos`.`Produit` (`id_produit`),
  CONSTRAINT `panier_ibfk_3`
    FOREIGN KEY (`id_coffret`)
    REFERENCES `Winos`.`Coffret` (`id_coffret`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Winos`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Winos`.`Commande` (
  `id_commande` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `id_client` MEDIUMINT NOT NULL,
  `id_produit` MEDIUMINT NULL DEFAULT NULL,
  `id_coffret` MEDIUMINT NULL DEFAULT NULL,
  `etat_commande` CHAR(55) NULL DEFAULT NULL,
  PRIMARY KEY (`id_commande`),
  INDEX `id_client` (`id_client` ASC) VISIBLE,
  INDEX `id_produit` (`id_produit` ASC) VISIBLE,
  INDEX `id_coffret` (`id_coffret` ASC) VISIBLE,
  CONSTRAINT `commande_ibfk_1`
    FOREIGN KEY (`id_client`)
    REFERENCES `Winos`.`Panier` (`id_client`),
  CONSTRAINT `commande_ibfk_2`
    FOREIGN KEY (`id_produit`)
    REFERENCES `Winos`.`Panier` (`id_produit`),
  CONSTRAINT `commande_ibfk_3`
    FOREIGN KEY (`id_coffret`)
    REFERENCES `Winos`.`Panier` (`id_coffret`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Winos`.`Produits_Coffret`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Winos`.`Produits_Coffret` (
  `id_produit` MEDIUMINT NOT NULL,
  `id_coffret` MEDIUMINT NOT NULL,
  INDEX `id_coffret` (`id_coffret` ASC) VISIBLE,
  INDEX `id_produit` (`id_produit` ASC) VISIBLE,
  CONSTRAINT `produits_coffret_ibfk_1`
    FOREIGN KEY (`id_coffret`)
    REFERENCES `Winos`.`Coffret` (`id_coffret`),
  CONSTRAINT `produits_coffret_ibfk_2`
    FOREIGN KEY (`id_produit`)
    REFERENCES `Winos`.`Produit` (`id_produit`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Winos`.`Promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Winos`.`Promotion` (
  `id_promo` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `pourcentage` MEDIUMINT NULL DEFAULT NULL,
  `code_promo` CHAR(55) NULL DEFAULT NULL,
  PRIMARY KEY (`id_promo`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
